### PR TITLE
implement 400 excpetion on deserialization failure

### LINKED ISSUE #99: Return `400` errors on deserialization failure
## Feature Request

Until we have full Pydantic-compliant models (#98), we rely on custom deserialization in the routes, e.g.:

```python
ballots = [PlaintextBallot.from_json_object(ballot) for ballot in request.ballots]
```

If this deserialization fails, however, it manifests as an opaque `500` error to the client.  We should capture deserialization errors and send a `400` with as much information as possible.

### PR DESCRIPTION
**Pull request by gagandeepp**
[//]: # (🚨 Please review the CONTRIBUTING.md in this repository. 💔Thank you!)

### Issue
Fixes https://github.com/microsoft/electionguard-api-python/issues/99

### Description
Add raise exception clause with 400 status for the deserialisation failure

### Testing
Hit Post Encrypt endpoint with incorrect request model

### CODE REVIEW

**Comment by gagandeepp** [comment]
@keithrfung please review

**Review by lprichar — DISMISSED** [review]
lgtm, thank you!

**Comment by lprichar** [comment]
@gagandeepp please fix linting error

**Comment by gagandeepp** [comment]
@lprichar can you please review this?
If you are facing issue while reviewing please add HACKTOBERFEST-ACCEPTED label to the issue ,so that you can review this later

**Comment by gagandeepp** [comment]
@lprichar please review this

**Comment by gagandeepp** [comment]
@lprichar pleae review

**Pull request closed without merging**
